### ISSUE TITLE
FMD : libblas module issue

### ISSUE THREAD

**Issue by bazinski** [SouthAfricaDigitalScience/FMD-codes-from-T.-Neff-#25]
running an arbitrarly chosen binary of fmd.

gnode-2-20:~ $ /cvmfs/fastrepo.sagrid.ac.za/generic/sl6/x86_64/FMD/0.1/bin/recalcenergy

/cvmfs/fastrepo.sagrid.ac.za/generic/sl6/x86_64/FMD/0.1/bin/recalcenergy: error while loading shared libraries: libblas.so.3: cannot open shared object file: No such file or directory

**Comment by brucellino** [comment]
Can you show your modules please ? 
Mine are : 

```
module add FMD
module list
Currently Loaded Modulefiles:
  1) ncurses/5.9               3) mpfr/3.1.2                5) gcc/5.1.0                 7) openmpi/1.8.8-gcc-5.1.0   9) FMD/0.1
  2) gmp/6.1.0                 4) mpc/1.0.1                 6) torque/2.5.13-gcc-5.1.0   8) lapack/3.6.0-gcc-5.1.0
```

**Comment by brucellino** [comment]
I can run recalcenergy fine on my laptop - 

```
ecalcenergy AV18-UsrgD2000f-v11ls-2.0.int -o He4.fmd 
... reading Interaction from file AV18-UsrgD2000f-v11ls-2.0.int
... reading Parameters from file He4.fmd
... Ozzz:  0.00000
... writing Parameters to file He4.fmd
```

So, either this is sl6-dependent (ie, modulefile is broken for SL6) or your modules are wrong...

**Comment by bazinski** [comment]
openblas/0.2.15-gcc-5.1.0 is there and when included manually via 

module add openblas/0.2.15-gcc-5.1.0

problem persists

 module list
Currently Loaded Modulefiles:
ModuleCmd_List.c(146):FATAL:996: The environment variables LOADEDMODULES and _LMFILES_ have inconsistent lengths.

might be a local issue

**Comment by brucellino** [comment]
ok, actually dealing with modules and the environment in general should be taken care of better. I will add something to fastrepo to help with the setup.

**Comment by bazinski** [comment]
module add FMD/0.1 
root@gnode-2-20:~ $ module list
Currently Loaded Modulefiles:
  1) ncurses/5.9               3) mpfr/3.1.2                5) gcc/5.1.0                 7) openmpi/1.8.8-gcc-5.1.0   9) FMD/0.1
  2) gmp/6.1.0                 4) mpc/1.0.1                 6) torque/2.5.13-gcc-5.1.0   8) lapack/3.6.0-gcc-5.1.0
root@gnode-2-20:~ $ ldd /cvmfs/fastrepo.sagrid.ac.za/generic/sl6/x86_64/FMD/0.1/bin/recalcenergy
    linux-vdso.so.1 =>  (0x00007ffd25dfa000)
    liblapack.so.3 => /usr/lib64/atlas/liblapack.so.3 (0x00007f4dece1b000)
    libblas.so.3 => not found
    libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x00007f4decb29000)
    libm.so.6 => /lib64/libm.so.6 (0x000000379a200000)
    libz.so.1 => /lib64/libz.so.1 (0x000000379aa00000)
    libc.so.6 => /lib64/libc.so.6 (0x0000003799600000)
    libf77blas.so.3 => /usr/lib64/atlas/libf77blas.so.3 (0x00007f4dec90a000)
    libcblas.so.3 => /usr/lib64/atlas/libcblas.so.3 (0x00007f4dec6ea000)
    /lib64/ld-linux-x86-64.so.2 (0x0000003799200000)
    libatlas.so.3 => /usr/lib64/atlas/libatlas.so.3 (0x00007f4debfdc000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003799e00000)

**Comment by bazinski** [comment]
adding openblas module manually ....

module add openblas/0.2.15-gcc-5.1.0
root@gnode-2-20:~ $ ldd /cvmfs/fastrepo.sagrid.ac.za/generic/sl6/x86_64/FMD/0.1/bin/recalcenergy
    linux-vdso.so.1 =>  (0x00007fff6cdc7000)
    liblapack.so.3 => /usr/lib64/atlas/liblapack.so.3 (0x00007f06221ba000)
    libblas.so.3 => not found
    libgfortran.so.3 => /usr/lib64/libgfortran.so.3 (0x00007f0621ec8000)
    libm.so.6 => /lib64/libm.so.6 (0x000000379a200000)
    libz.so.1 => /lib64/libz.so.1 (0x000000379aa00000)
    libc.so.6 => /lib64/libc.so.6 (0x0000003799600000)
    libf77blas.so.3 => /usr/lib64/atlas/libf77blas.so.3 (0x00007f0621ca9000)
    libcblas.so.3 => /usr/lib64/atlas/libcblas.so.3 (0x00007f0621a89000)
    /lib64/ld-linux-x86-64.so.2 (0x0000003799200000)
    libatlas.so.3 => /usr/lib64/atlas/libatlas.so.3 (0x00007f062137b000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003799e00000)

**Comment by bazinski** [comment]
ls /cvmfs/fastrepo.sagrid.ac.za/generic/sl6/x86_64/openblas/0.2.15-gcc-5.1.0/lib/
cmake/                           libopenblas_nehalemp-r0.2.15.a   libopenblas.so  
libopenblas.a                    libopenblas_nehalemp-r0.2.15.so  libopenblas.so.0

**Comment by bazinski** [comment]
sorted it was an issue with libraries and lapack,
Shot Bruce for the bash-setup.sh in cvmfs/fastrepo.sagrid.ac.za/

module add FMD/0.1
root@gnode-2-20:/ $ module list
Currently Loaded Modulefiles:
  1) ncurses/5.9               3) mpfr/3.1.2                5) gcc/5.1.0                 7) openmpi/1.8.8-gcc-5.1.0   9) FMD/0.1
  2) gmp/6.1.0                 4) mpc/1.0.1                 6) torque/2.5.13-gcc-5.1.0   8) lapack/3.6.0-gcc-5.1.0
root@gnode-2-20:/ $ ldd /cvmfs/fastrepo.sagrid.ac.za/generic/sl6/x86_64/FMD/0.1/bin/recalcenergy
    linux-vdso.so.1 =>  (0x00007ffe86ee5000)
    liblapack.so.3 => /cvmfs/fastrepo.sagrid.ac.za/generic/sl6/x86_64/lapack/3.6.0-gcc-5.1.0/lib64/liblapack.so.3 (0x00007efef4b0d000)
    libblas.so.3 => /cvmfs/fastrepo.sagrid.ac.za/generic/sl6/x86_64/lapack/3.6.0-gcc-5.1.0/lib64/libblas.so.3 (0x00007efef488e000)
    libgfortran.so.3 => /cvmfs/fastrepo.sagrid.ac.za/generic/sl6/x86_64/gcc/5.1.0/lib64/libgfortran.so.3 (0x00007efef456d000)
    libm.so.6 => /lib64/libm.so.6 (0x000000379a200000)
    libz.so.1 => /lib64/libz.so.1 (0x000000379aa00000)
    libc.so.6 => /lib64/libc.so.6 (0x0000003799600000)
    libgcc_s.so.1 => /cvmfs/fastrepo.sagrid.ac.za/generic/sl6/x86_64/gcc/5.1.0/lib64/libgcc_s.so.1 (0x00007efef4344000)
    libquadmath.so.0 => /cvmfs/fastrepo.sagrid.ac.za/generic/sl6/x86_64/gcc/5.1.0/lib64/libquadmath.so.0 (0x00007efef4106000)
    /lib64/ld-linux-x86-64.so.2 (0x0000003799200000)
root@gnode-2-20:/ $ /cvmfs/fastrepo.sagrid.ac.za/generic/sl6/x86_64/FMD/0.1/bin/recalcenergy

usage: /cvmfs/fastrepo.sagrid.ac.za/generic/sl6/x86_64/FMD/0.1/bin/recalcenergy interaction parafile

   -o              overwrite parameter file

**Comment by brucellino** [comment]
Just as a reference, this is also in https://github.com/AAROC/CODE-RADE/blob/master/modules.sh - but it's nice to have the setup script in the actual repo.
